#define JAYMOD_name           "PARAZIT-Mod"
#define JAYMOD_namef          "PARAZIT-Mod"
#define JAYMOD_namex          "^1PA^3RAZ^4IT^2-Mod"
#define JAYMOD_website        "http://parazit.ro"
#define JAYMOD_irc            "irc.freenode.net #parazitmod"
#define JAYMOD_author         "Gavrila"
#define JAYMOD_copyright      "Copyright (c) 2011-2018 Gavrila. All Rights Reserved."
#define JAYMOD_versionMajor   "2"
#define JAYMOD_versionMinor   "2"
#define JAYMOD_versionPoint   "0"
#define JAYMOD_versionHex     0x02020000
#define JAYMOD_buildDate      "Fri Jan 20 23:05:44 PST 2017"
#define JAYMOD_buildStability "stable"
#define JAYMOD_buildTarget    "windows-release"
#define JAYMOD_repoURL        ""
#define JAYMOD_repoUUID       "19d76e98-4125-d806-76c2-ce57b7db7bff"
#define JAYMOD_repoRev        "3"
#define JAYMOD_repoLCRev      "3"
#define JAYMOD_repoLCDate     "2016-08-10 11:58:39 -0700 (Wed, 10 Aug 2016)"
#define JAYMOD_platformName   "Windows"
#define JAYMOD_platformNamef  "windows"
#define JAYMOD_title          "PARAZIT-Mod 2.2.0"
#define JAYMOD_titlex         "^1PA^3RAZ^4IT^2-Mod ^22.2.0"
#define JAYMOD_version        "2.2.0"
#define JAYMOD_versionx       "^22.2.0"
#define JAYMOD_packageBase    "parazit-2.2.0"
#define JAYMOD_packageBasev   "parazit-2.2.0-windows-release"
#define JAYMOD_pk3            "parazit-2.2.0.pk3"

#define JAYMOD_WINDOWS
#define JAYMOD_STABLE
